category: forensics
points:   500
name:     Странный вирус
author:   nsychev
description: >
    <p><i>Перед решением ознакомьтесь с тасками <a href="/tasks/guest">Гостевой режим</a> и <a href="/tasks/backdoor">Бэкдор</a>.</i></p>
    <p>Вирус на компьютере Петра успешно работал лишь короткий интервал времени, однако хакеры
    успели получить достаточно тайных киберсекретов компании.</p>
    <p>Однако, они сами совершенно не позаботились о безопасности своих серверов. Поэтому скоро
    эти секреты получим и мы. Правда же?</p>
    <p><i>Подсказка:</i> какую базу данных используют хакеры?</p>
    <p><i>В этот таск следует сдавать флаг 6.</i></p>
flags:
    - "ugra_mysq1_1n53cur17y"
