category: forensics
points:   300
name:     Try again
author:   nsychev
description: >
    <p><i>Перед решением ознакомьтесь с таском <a href="/tasks/guest">Гостевой режим</a>.</i></p>
    <p>Пётр недавно выиграл тендер на обработку конфиденциальной информации. Однако, со слов
    анонимного источника в компании, на совещании говорили, что партнеры ещё не передали информацию
    Петру. Возможно, информация появилась после совещания?</p>
    <p><i>В этот таск следует сдавать флаг 5.</i></p>
flags:
    - "ugra_h1dden_a77tribu7es"
